apiVersion: v1
kind: Pod
metadata: 
     name: mypod1
spec: 
  containers: 
         - name: mycontainer
           image: nginx:latest
           ports: 
              - name: http
                containerPort: 80
                protocol: TCP
