apiVersion: v1
kind: Pod
metadata: 
     name: mypod
spec: 
  containers: 
         -name: mycontainer
          image: nginx:latest
          ports: 
             -name: http
             containerPort: 80
             protocol: TCP
