apiVersion: v1
kind: Pod
metadata: 
     name: clusterip
spec: 
  selector: 
         -name: mycontainer
          image: nginx:latest
          ports: 
             -name: http
             containerPort: 80
             protocol: TCP
