apiVersion: v1
kind: Service
metadata: 
     name: loadbalancer
spec: 
  selector: 
       app: mypod1
  type: LoadBalancer     
  ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      name: nginx
