apiVersion: v1
kind: Pod
metadata: 
     name: clusterip
spec: 
  selector: 
       app: mypod
  type: ClusterIP     
  ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      name: nginx
